### 201 [preorders]
GET http://localhost:5000/api/phones/1/preorders HTTP/1.1

### 404
GET http://localhost:5000/api/phones/0/preorders HTTP/1.1

### 200 []
GET http://localhost:5000/api/phones/10/preorders HTTP/1.1